const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Design Homepage",
        taskDescription: "Create a responsive homepage layout.",
        taskDate: "2025-02-01",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix Navbar Issue",
        taskDescription: "Resolve the overlapping issue in mobile view.",
        taskDate: "2025-02-02",
        category: "Bug Fixing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Implement Dark Mode",
        taskDescription: "Add a toggle button for dark mode support.",
        taskDate: "2025-02-03",
        category: "Feature",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      
    ],
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    firstName: "Vihaan",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Optimize API Calls",
        taskDescription: "Reduce API response time for better performance.",
        taskDate: "2025-02-04",
        category: "Performance",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Unit Testing for Authentication",
        taskDescription: "Write test cases for user authentication module.",
        taskDate: "2025-02-05",
        category: "Testing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Database Migration",
        taskDescription: "Migrate user database to PostgreSQL.",
        taskDate: "2025-02-06",
        category: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Update User Profile UI",
        taskDescription: "Redesign user profile page with better UX.",
        taskDate: "2025-02-07",
        category: "UI/UX",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 3,
    firstName: "Ishaan",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Refactor Backend Code",
        taskDescription: "Improve code structure and remove unused functions.",
        taskDate: "2025-02-08",
        category: "Backend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Create Admin Dashboard",
        taskDescription: "Develop an interactive admin panel with analytics.",
        taskDate: "2025-02-09",
        category: "Admin",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix Session Timeout Issue",
        taskDescription:
          "Ensure users are logged out after 30 minutes of inactivity.",
        taskDate: "2025-02-10",
        category: "Security",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Implement Two-Factor Authentication",
        taskDescription: "Enhance security by adding 2FA support.",
        taskDate: "2025-02-11",
        category: "Security",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 4,
    firstName: "rohan",
    email: "employe@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Design Homepage",
        taskDescription: "Create a responsive homepage layout.",
        taskDate: "2025-02-01",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix Navbar Issue",
        taskDescription: "Resolve the overlapping issue in mobile view.",
        taskDate: "2025-02-02",
        category: "Bug Fixing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Implement Dark Mode",
        taskDescription: "Add a toggle button for dark mode support.",
        taskDate: "2025-02-03",
        category: "Feature",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstName: "sohan",
    email: "emplo@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Optimize API Calls",
        taskDescription: "Reduce API response time for better performance.",
        taskDate: "2025-02-04",
        category: "Performance",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Unit Testing for Authentication",
        taskDescription: "Write test cases for user authentication module.",
        taskDate: "2025-02-05",
        category: "Testing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Database Migration",
        taskDescription: "Migrate user database to PostgreSQL.",
        taskDate: "2025-02-06",
        category: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Update User Profile UI",
        taskDescription: "Redesign user profile page with better UX.",
        taskDate: "2025-02-07",
        category: "UI/UX",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
];
const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setlocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getlocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
